name: SonarQube Scan Only

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: MyWebApp  # Eğer kodların "MyWebApp" klasöründeyse
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=my-PHP-web-app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
