name: CI/CD workflow for PHP Code Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --working-dir=MyWebApp

      - name: Run PHPStan Static Analysis
        run: vendor/bin/phpstan analyse MyWebApp --level=5

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: MyWebApp
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=my-php-project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
